import User from '../models/User.js'
import jwt from 'jsonwebtoken'
import bcrypt from 'bcryptjs'
import Chat from '../models/Chat.js'

// Generate JWT for authetication of new user
const generateToken = (id) => {
    return jwt.sign({ id }, process.env.JWT_SECRET, {
        expiresIn: '2d'
    })
}

// API to register user
export const registerUser = async (req, res) => {
    const { name, email, password } = req.body
    try {
        const userExists = await User.findOne({ email })
        //user exists
        if (userExists) {
            return res.json({ success: false, message: 'User already exists.' })
        }
        // user does not exist-> create
        const user = await User.create({ name, email, password })
        // generate token for auth
        const token = generateToken(user._id) // "_id" is autogenerated by mongoDB
        res.json({ success: true, token })

    } catch (error) {
        return res.json({ success: false, message: error.message })

    }
}

// API to login user
export const loginUser = async (req, res) => {
    const { email, password } = req.body
    try {
        const user = await User.findOne({ email })
        // user exists
        if (user) {
            // check password
            const isMatch = await bcrypt.compare(password, user.password)
            if (isMatch) {
                const token = generateToken(user._id)
                return res.json({ success: true, token })
            }
        }
        return res.json({ success: false, message: 'Invalid Username or Password.' })
    } catch (error) {
        return res.json({ success: false, message: error.message })

    }
}

// API to get user
export const getUser = async (req, res) => {
    try {
        const user = req.user // req does not have "user" property yet, it will be added using middleware
        return res.json({ success: true, user })
    } catch (error) {
        return res.json({ success: false, message: error.message })

    }
}

//API to get published images
export const getPublishedImages = async(req, res)=>{
    try{
        const publishedImageMessages= await Chat.aggregate([
            {$unwind:"$messages"},
            {
                $match:{
                    "messages.isImage":true,
                    "messages.isPublished": true,
                }
            },
            {
                $project:{
                    _id:0,
                    imageUrl:"$messages.content",
                    userName: "$userName",
                }
            }
        ])
        res.json({success:true, images: publishedImageMessages.reverse()})
    }catch(error){
        res.json({success:false, message:error.message})
    }
}